### ISSUE TITLE
Getting an error when submitting form: DateTimeImmutable not found

### ISSUE THREAD

**Issue by noelhawat** [SymfonyCasts/reset-password-bundle#129]
Not sure what's missing, but when I submit the password reset form I get this error: 
`The class 'DateTimeImmutable' was not found in the chain configured namespaces App\Entity`

I generated the code using the `make:reset-password` command

I use the `DateTimeImmutable` in other entities just fine.

It looks like this is where it's failing:
```php
public function removeExpiredResetPasswordRequests(): int
    {
        $time = new \DateTimeImmutable('-1 week');
        $query = $this->createQueryBuilder('t')
            ->delete()
            ->where('t.expiresAt <= :time')
            ->setParameter('time', $time)
            ->getQuery()
        ;
        return $query->execute();
    }
```

I tried overriding the function to use `DateTime` but got the same error.

this is the reset_password.yaml:
```yaml
symfonycasts_reset_password:
  request_password_repository: App\Repository\ResetPasswordRequestRepository
  lifetime: 3600
  throttle_limit: 3600
  enable_garbage_collection: true
```
