### ISSUE TITLE
How to set request lifetime manually?

### ISSUE THREAD

**Issue by virtualize** [SymfonyCasts/reset-password-bundle#177]
**Use case**: For some users we create predefined accounts they can claim. For each user we create a password reset request, so the user must simply set its own password and can then login.

For these cases the default TTL (used for normal registrations) is simply too short and we want to set a custom one.

Thanks for any pointers.

**Comment by jrushlow** [comment]
Howdy @virtualize and thanks for using our bundle. Check out our docs on configuring the ResetPasswordBundle https://github.com/SymfonyCasts/reset-password-bundle#configuration

In short you'll want to set the `lifetime` parameter in the `reset_password.yaml` configuration file to a value that's appropriate to your use case.

**Comment by virtualize** [comment]
@jrushlow Thanks for the fast response. 

I've seen the docs on configuration and I've already set the appropriate values for users resetting their password.
But in the use case describe above, we manually create a password reset request, where we need to set a much longer request lifetime. 

We want to set different lifetimes for different use cases.

**Comment by virtualize** [comment]
For anyone interested, here is how I solved it.

Define an additional custom password helper service in `services.yaml`, add custom lifetime
```yaml
    # custom password reset helper with long request lifetime
    symfonycasts.reset_password.helper.longlife:
        class: SymfonyCasts\Bundle\ResetPassword\ResetPasswordHelper
        arguments:
            - '@symfonycasts.reset_password.token_generator'
            - '@symfonycasts.reset_password.cleaner'
            - '@App\Repository\User\ResetPasswordRequestRepository'
            - 2592000 # 30 days
            - 300
    # bind our service to a named alias, to use it inject 'ResetPasswordHelperInterface $longlifeResetPasswordHelper'
    SymfonyCasts\Bundle\ResetPassword\ResetPasswordHelperInterface $longlifeResetPasswordHelper: '@symfonycasts.reset_password.helper.longlife'
```

Now we have two password reset helpers.

Then we can inject this custom one into any class like this
```php
    public function __construct(ResetPasswordHelperInterface $longlifeResetPasswordHelper) 
    {
        $this->resetPasswordHelper = $longlifeResetPasswordHelper;
    }
```
